STR_CLIENT_INFO = "Clients Info"
STR_MEDIA_CONTENT = "Media Contents"
STR_HDMI_IN = "HDMI-In"
STR_LED_SETTING = "LED Setting"
STR_CMS = "CMS"
STR_TEST = "TEST"
STR_TEST_B = "TestB"

ICLED_TYPE_AOS = "AOS"
ICLED_TYPE_ANAPEXL = "ANAPEX_L"
ICLED_TYPE_ANAPEXM = "ANAPEX_M"



